import React, { useState } from 'react';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { Header, SectionTitle } from '../components/Primitives';
import { colors } from '../theme';

export function CardsScreen() {
  const [frozen, setFrozen] = useState(false); const [online, setOnline] = useState(true); const [abroad, setAbroad] = useState(true);
  return <ScrollView contentContainerStyle={styles.content}><Header title="Tus tarjetas" subtitle="Control total y seguro" />
    <LinearGradient colors={frozen ? ['#7C8683', '#4B5351'] : ['#123E35', '#071F1A']} style={styles.card}><View style={styles.top}><Text style={styles.brand}>ÁUREA</Text><Ionicons name="wifi-outline" size={23} color="#FFFFFFAA" /></View><Text style={styles.number}>5412   8821   4093   4821</Text><View style={styles.bottom}><View><Text style={styles.mini}>TITULAR</Text><Text style={styles.white}>DANIELA MARTÍN</Text></View><View><Text style={styles.mini}>CADUCA</Text><Text style={styles.white}>09/29</Text></View><Text style={styles.mc}>●●</Text></View>{frozen && <View style={styles.frozen}><Ionicons name="snow-outline" size={18} color={colors.white} /><Text style={styles.frozenText}>Tarjeta congelada</Text></View>}</LinearGradient>
    <View style={styles.actions}><Action icon="eye-outline" text="Ver datos" /><Action icon="keypad-outline" text="Ver PIN" /><Action icon="settings-outline" text="Límites" /></View>
    <View style={styles.settings}><SectionTitle>Configuración</SectionTitle><Toggle icon="snow-outline" title="Congelar tarjeta" subtitle="Bloquea cualquier operación" value={frozen} onValueChange={setFrozen} /><Toggle icon="globe-outline" title="Compras online" subtitle="Pagos en comercios digitales" value={online} onValueChange={setOnline} /><Toggle icon="airplane-outline" title="Uso en el extranjero" subtitle="Pagos fuera de España" value={abroad} onValueChange={setAbroad} /></View>
    <View style={styles.alert}><Ionicons name="shield-checkmark-outline" size={24} color={colors.green} /><View><Text style={styles.alertTitle}>Todo bajo control</Text><Text style={styles.alertBody}>No hemos detectado actividad inusual.</Text></View></View>
  </ScrollView>;
}
function Action({ icon, text }: { icon: keyof typeof Ionicons.glyphMap; text: string }) { return <Pressable style={styles.action}><Ionicons name={icon} size={21} color={colors.green} /><Text style={styles.actionText}>{text}</Text></Pressable>; }
function Toggle({ icon, title, subtitle, value, onValueChange }: { icon: keyof typeof Ionicons.glyphMap; title: string; subtitle: string; value: boolean; onValueChange: (v: boolean) => void }) { return <View style={styles.toggle}><View style={styles.toggleIcon}><Ionicons name={icon} size={20} color={colors.green} /></View><View style={{ flex: 1 }}><Text style={styles.toggleTitle}>{title}</Text><Text style={styles.toggleSub}>{subtitle}</Text></View><Switch accessibilityLabel={title} value={value} onValueChange={onValueChange} trackColor={{ true: colors.green, false: '#CCD3D0' }} /></View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 30 }, card: { height: 210, margin: 20, borderRadius: 25, padding: 23, justifyContent: 'space-between' }, top: { flexDirection: 'row', justifyContent: 'space-between' }, brand: { color: colors.accent, fontWeight: '800', letterSpacing: 2, fontSize: 17 }, number: { color: colors.white, fontSize: 18, letterSpacing: 2 }, bottom: { flexDirection: 'row', alignItems: 'flex-end', gap: 26 }, mini: { color: '#FFFFFF88', fontSize: 8, letterSpacing: 1 }, white: { color: colors.white, fontSize: 11, marginTop: 4 }, mc: { color: colors.accent, fontSize: 22, marginLeft: 'auto' }, frozen: { position: 'absolute', top: 82, alignSelf: 'center', flexDirection: 'row', alignItems: 'center', gap: 7, backgroundColor: '#0B211CDD', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18 }, frozenText: { color: colors.white, fontWeight: '700', fontSize: 12 }, actions: { flexDirection: 'row', marginHorizontal: 20, justifyContent: 'space-between' }, action: { width: '31%', paddingVertical: 15, backgroundColor: colors.white, borderRadius: 16, alignItems: 'center', gap: 6, borderWidth: 1, borderColor: colors.line }, actionText: { color: colors.ink, fontSize: 11, fontWeight: '600' }, settings: { margin: 20, backgroundColor: colors.white, borderRadius: 20, padding: 17 }, toggle: { flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 13, borderBottomWidth: 1, borderColor: colors.line }, toggleIcon: { width: 39, height: 39, borderRadius: 12, backgroundColor: colors.softGreen, alignItems: 'center', justifyContent: 'center' }, toggleTitle: { color: colors.ink, fontWeight: '600' }, toggleSub: { color: colors.muted, fontSize: 11, marginTop: 3 }, alert: { flexDirection: 'row', marginHorizontal: 20, padding: 16, gap: 12, backgroundColor: colors.softGreen, borderRadius: 17 }, alertTitle: { color: colors.green, fontWeight: '700' }, alertBody: { color: colors.muted, fontSize: 12, marginTop: 3 } });
