import React, { useState } from 'react';
import { Ionicons } from '@expo/vector-icons';
import { KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { colors } from '../theme';

export function LoginScreen({ onLogin }: { onLogin: () => void }) {
  const [email, setEmail] = useState('daniela@demo.aurea.app'); const [password, setPassword] = useState('demo1234'); const [visible, setVisible] = useState(false); const [loading, setLoading] = useState(false);
  const login = () => { if (!email || !password) return; setLoading(true); setTimeout(onLogin, 650); };
  return <LinearGradient colors={['#071F1A', '#123E35']} style={styles.page}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.inner}>
    <View style={styles.brand}><View style={styles.mark}><Text style={styles.markText}>A</Text></View><Text style={styles.logo}>ÁUREA</Text><Text style={styles.tagline}>Tu dinero, con otra perspectiva.</Text></View>
    <View style={styles.sheet}><Text style={styles.title}>Te damos la bienvenida</Text><Text style={styles.subtitle}>Accede a tu espacio financiero</Text>
      <Text style={styles.label}>Correo electrónico</Text><View style={styles.inputWrap}><Ionicons name="mail-outline" size={19} color={colors.muted} /><TextInput accessibilityLabel="Correo electrónico" autoComplete="email" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} style={styles.input} /></View>
      <Text style={styles.label}>Contraseña</Text><View style={styles.inputWrap}><Ionicons name="lock-closed-outline" size={19} color={colors.muted} /><TextInput accessibilityLabel="Contraseña" autoComplete="password" value={password} onChangeText={setPassword} secureTextEntry={!visible} style={styles.input} /><Pressable accessibilityRole="button" accessibilityLabel={visible ? 'Ocultar contraseña' : 'Mostrar contraseña'} onPress={() => setVisible(v => !v)}><Ionicons name={visible ? 'eye-off-outline' : 'eye-outline'} size={20} color={colors.muted} /></Pressable></View>
      <Pressable><Text style={styles.forgot}>¿Has olvidado tu contraseña?</Text></Pressable><Pressable accessibilityRole="button" onPress={login} disabled={loading} style={styles.button}><Text style={styles.buttonText}>{loading ? 'Accediendo…' : 'Acceder'}</Text><Ionicons name="arrow-forward" color={colors.white} size={19} /></Pressable>
      <View style={styles.demo}><Ionicons name="information-circle-outline" size={18} color={colors.green} /><Text style={styles.demoText}>Credenciales precargadas para la demostración.</Text></View>
    </View><Text style={styles.legal}>Demo de portafolio · No procesa dinero real</Text>
  </KeyboardAvoidingView></LinearGradient>;
}
const styles = StyleSheet.create({ page: { flex: 1 }, inner: { flex: 1, justifyContent: 'flex-end' }, brand: { alignItems: 'center', flex: 1, justifyContent: 'center' }, mark: { width: 72, height: 72, borderRadius: 25, backgroundColor: colors.accent, alignItems: 'center', justifyContent: 'center' }, markText: { fontSize: 42, fontWeight: '900', fontStyle: 'italic', color: colors.green }, logo: { color: colors.white, fontSize: 24, fontWeight: '800', letterSpacing: 5, marginTop: 15 }, tagline: { color: '#FFFFFF99', marginTop: 7 }, sheet: { backgroundColor: colors.canvas, borderTopLeftRadius: 32, borderTopRightRadius: 32, padding: 26, paddingBottom: 22 }, title: { color: colors.ink, fontSize: 24, fontWeight: '800' }, subtitle: { color: colors.muted, marginTop: 5, marginBottom: 20 }, label: { color: colors.ink, fontSize: 12, fontWeight: '700', marginBottom: 7, marginTop: 12 }, inputWrap: { height: 50, borderWidth: 1, borderColor: colors.line, borderRadius: 14, backgroundColor: colors.white, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 13 }, input: { flex: 1, height: '100%', marginLeft: 9, color: colors.ink }, forgot: { color: colors.green, fontWeight: '700', fontSize: 12, textAlign: 'right', marginVertical: 13 }, button: { height: 54, backgroundColor: colors.green, borderRadius: 16, flexDirection: 'row', gap: 10, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: colors.white, fontWeight: '700', fontSize: 15 }, demo: { flexDirection: 'row', gap: 7, alignItems: 'center', backgroundColor: colors.softGreen, padding: 11, borderRadius: 12, marginTop: 14 }, demoText: { color: colors.green, fontSize: 11 }, legal: { color: '#FFFFFF77', textAlign: 'center', fontSize: 10, paddingVertical: 12 } });
