import React from 'react';
import { Ionicons } from '@expo/vector-icons';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Header } from '../components/Primitives';
import { colors } from '../theme';

export function ProfileScreen({ logout }: { logout: () => void }) {
  return <ScrollView contentContainerStyle={styles.content}><Header title="Perfil" subtitle="Cuenta y seguridad" />
    <View style={styles.person}><View style={styles.avatar}><Text style={styles.initials}>DM</Text></View><Text style={styles.name}>Daniela Martín</Text><Text style={styles.email}>daniela@demo.aurea.app</Text><View style={styles.verified}><Ionicons name="checkmark-circle" size={13} color="#187552" /><Text style={styles.verifiedText}>Identidad verificada</Text></View></View>
    <View style={styles.menu}><Item icon="person-outline" title="Datos personales" /><Item icon="shield-checkmark-outline" title="Seguridad y acceso" badge="2FA" /><Item icon="people-outline" title="Destinatarios" /><Item icon="notifications-outline" title="Notificaciones" /><Item icon="document-text-outline" title="Documentos" /><Item icon="help-circle-outline" title="Ayuda y soporte" /></View>
    <View style={styles.audit}><Ionicons name="finger-print-outline" size={24} color={colors.green} /><View style={{ flex: 1 }}><Text style={styles.auditTitle}>Último acceso</Text><Text style={styles.auditText}>Hoy, 09:31 · iPhone de Daniela</Text></View><Text style={styles.safe}>Seguro</Text></View>
    <Pressable onPress={logout} style={styles.logout}><Ionicons name="log-out-outline" size={20} color={colors.red} /><Text style={styles.logoutText}>Cerrar sesión</Text></Pressable><Text style={styles.version}>Áurea Mobile · versión 1.0.0 · Entorno demo</Text>
  </ScrollView>;
}
function Item({ icon, title, badge }: { icon: keyof typeof Ionicons.glyphMap; title: string; badge?: string }) { return <Pressable style={styles.item}><View style={styles.itemIcon}><Ionicons name={icon} size={20} color={colors.green} /></View><Text style={styles.itemTitle}>{title}</Text>{badge && <Text style={styles.badge}>{badge}</Text>}<Ionicons name="chevron-forward" size={18} color="#A4AEAA" /></Pressable>; }
const styles = StyleSheet.create({ content: { paddingBottom: 30 }, person: { alignItems: 'center', paddingVertical: 18 }, avatar: { width: 78, height: 78, borderRadius: 28, backgroundColor: '#F2E7CF', alignItems: 'center', justifyContent: 'center' }, initials: { color: colors.green, fontSize: 24, fontWeight: '800' }, name: { fontSize: 22, fontWeight: '800', color: colors.ink, marginTop: 12 }, email: { color: colors.muted, marginTop: 4 }, verified: { flexDirection: 'row', gap: 4, marginTop: 8, backgroundColor: colors.softGreen, paddingHorizontal: 9, paddingVertical: 4, borderRadius: 10 }, verifiedText: { color: '#187552', fontSize: 10, fontWeight: '700' }, menu: { margin: 20, backgroundColor: colors.white, borderRadius: 20, paddingHorizontal: 16 }, item: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 13, borderBottomWidth: 1, borderColor: colors.line }, itemIcon: { width: 39, height: 39, borderRadius: 12, backgroundColor: '#F0F3F1', alignItems: 'center', justifyContent: 'center' }, itemTitle: { flex: 1, color: colors.ink, fontWeight: '600' }, badge: { backgroundColor: colors.softGreen, color: colors.green, paddingHorizontal: 7, paddingVertical: 3, borderRadius: 8, fontSize: 9, fontWeight: '800' }, audit: { marginHorizontal: 20, flexDirection: 'row', gap: 12, alignItems: 'center', padding: 16, borderRadius: 17, backgroundColor: colors.softGreen }, auditTitle: { color: colors.green, fontWeight: '700' }, auditText: { color: colors.muted, fontSize: 11, marginTop: 3 }, safe: { color: '#187552', fontSize: 11, fontWeight: '700' }, logout: { margin: 20, height: 50, borderWidth: 1, borderColor: '#EDCBCD', borderRadius: 15, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center' }, logoutText: { color: colors.red, fontWeight: '700' }, version: { textAlign: 'center', color: colors.muted, fontSize: 10 } });
